// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZ_walks.Data;

#nullable disable

namespace NZ_walks.Migrations
{
    [DbContext(typeof(NZ_walksDbContext))]
    [Migration("20260605024031_SeedAdditionalData")]
    partial class SeedAdditionalData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZ_walks.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("26673c5e-6874-4b02-abab-c6738de23d4a"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("d10fb12c-156f-48ad-b322-43ce9cbdf099"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("00759623-d7ae-4f73-acfc-8c7f6ece641d"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZ_walks.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("676da151-860e-4f21-ac56-6525659946f4"),
                            Code = "THR",
                            Name = "Tehran"
                        },
                        new
                        {
                            Id = new Guid("3682e0fa-371f-4eac-87ba-4149c4aff6a0"),
                            Code = "KRJ",
                            Name = "Karaj"
                        },
                        new
                        {
                            Id = new Guid("5e21f34e-1134-45c8-a4a2-b5710f687f34"),
                            Code = "SHZ",
                            Name = "Shiraz"
                        },
                        new
                        {
                            Id = new Guid("5ed936c1-046a-4ff3-b257-d1243e1efc8e"),
                            Code = "ESF",
                            Name = "Esfehan"
                        });
                });

            modelBuilder.Entity("NZ_walks.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZ_walks.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZ_walks.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZ_walks.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
